# Generated by Django 6.0.4 on 2026-05-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('SALE', 'Sale / Revenue'), ('PURCHASE', 'Purchase / Expense')], default='SALE', max_length=10)),
                ('amount_excl_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('amount_incl_gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('receipt_ref', models.CharField(blank=True, max_length=50, verbose_name='Receipt / Invoice Ref')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'Daily Ledger Entry',
                'verbose_name_plural': 'Daily Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('output_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('input_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to IRC'), ('PAID', 'Payment Confirmed'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('irc_reference', models.CharField(blank=True, max_length=50, verbose_name='IRC Reference Number')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_returns', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'GST Return',
                'verbose_name_plural': 'GST Returns',
                'ordering': ['-period_end'],
            },
        ),
    ]
