# Generated by Django 6.0.4 on 2026-05-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBTDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(default=2026)),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sbt_type', models.CharField(choices=[('FLAT', 'Flat Fee (K400) — Turnover < K50,000'), ('PERCENT', '2% of Turnover — Turnover K50k–K250k'), ('EXEMPT', 'Not Eligible — Turnover > K250,000')], max_length=10)),
                ('sbt_liability', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to IRC'), ('PAID', 'Payment Confirmed'), ('EXEMPT', 'Exempt / Threshold Exceeded'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=50)),
                ('irc_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbt_declarations', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'SBT Declaration',
                'verbose_name_plural': 'SBT Declarations',
                'ordering': ['-tax_year'],
                'unique_together': {('business', 'tax_year')},
            },
        ),
    ]
