# Generated by Django 6.0.4 on 2026-05-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('tin', models.CharField(help_text='IRC Tax Identification Number', max_length=20, unique=True, verbose_name='IRC TIN')),
                ('province', models.CharField(choices=[('NCD', 'National Capital District'), ('WNB', 'West New Britain'), ('ENB', 'East New Britain'), ('MRL', 'Manus'), ('NIP', 'New Ireland'), ('MBP', 'Milne Bay'), ('ORO', 'Oro (Northern)'), ('CHM', 'Chimbu (Simbu)'), ('EHP', 'Eastern Highlands'), ('WHP', 'Western Highlands'), ('JWK', 'Jiwaka'), ('HLA', 'Hela'), ('SHM', 'Southern Highlands'), ('EPW', 'Enga'), ('WPD', 'Western (Fly)'), ('GPL', 'Gulf'), ('CPM', 'Central'), ('SAN', 'Sandaun (West Sepik)'), ('ESP', 'East Sepik'), ('MPM', 'Morobe'), ('MDP', 'Madang'), ('BUK', 'Bougainville')], default='NCD', max_length=10)),
                ('industry', models.CharField(choices=[('RETAIL', 'Retail & Trade Store'), ('FOOD', 'Food & Beverage / Canteen'), ('TRANSPORT', 'Transport & Logistics'), ('AGRI', 'Agriculture & Farming'), ('CONSTRUCT', 'Construction & Building'), ('HEALTH', 'Health & Medical'), ('EDUCATION', 'Education & Training'), ('PROFESSIONAL', 'Professional Services'), ('TOURISM', 'Tourism & Hospitality'), ('TECH', 'Technology & ICT'), ('FISHING', 'Fishing & Marine'), ('MINING', 'Mining & Extraction'), ('OTHER', 'Other')], default='RETAIL', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gst_registered', models.BooleanField(default=False, verbose_name='GST Registered?')),
                ('gst_registration_number', models.CharField(blank=True, max_length=30)),
                ('gst_filing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly (turnover > K250,000)'), ('QUARTERLY', 'Quarterly')], default='QUARTERLY', max_length=10)),
                ('sbt_eligible', models.BooleanField(default=True, verbose_name='SBT Eligible?')),
                ('annual_turnover_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'ordering': ['business_name'],
            },
        ),
    ]
