# Generated by Django 6.0.4 on 2026-05-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='notify_days_before',
            field=models.IntegerField(default=3, help_text='Days before deadline to alert'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='notify_method',
            field=models.CharField(choices=[('SMS', 'SMS (Mobile)'), ('EMAIL', 'Email'), ('BOTH', 'Both SMS & Email'), ('NONE', 'No Notifications')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Business Owner'), ('ACCOUNTANT', 'External Accountant'), ('STAFF', 'Compliance Staff')], default='OWNER', max_length=20),
        ),
    ]
