# Generated by Django 6.0.4 on 2026-05-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('tin', models.CharField(blank=True, max_length=20, verbose_name='Employee TIN')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_resident', models.BooleanField(default=True, verbose_name='PNG Resident?')),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly')], default='FORTNIGHTLY', max_length=15)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('swt_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_remitted', models.BooleanField(default=False, verbose_name='SWT Remitted to IRC?')),
                ('remittance_ref', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='swt.employee')),
            ],
            options={
                'verbose_name': 'Payroll Entry',
                'verbose_name_plural': 'Payroll Entries',
                'ordering': ['-pay_period_end'],
            },
        ),
        migrations.CreateModel(
            name='SWTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Return Month (1st of month)')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_swt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to IRC'), ('PAID', 'Payment Confirmed'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('irc_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swt_returns', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'SWT Return',
                'verbose_name_plural': 'SWT Returns',
                'ordering': ['-month'],
            },
        ),
    ]
